.TH BITCOINOIL-CLI "1" "February 2016" "bitcoinoil-cli 0.12"
.SH NAME
bitcoinoil-cli \- a remote procedure call client for BitcoinOil Core. 
.SH SYNOPSIS
bitcoinoil-cli [options] <command> [params] \- Send command to BitcoinOil Core. 
.TP
bitcoinoil-cli [options] help \- Asks BitcoinOil Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the bitcoinoil-cli program. bitcoinoil-cli is an RPC client used to send commands to BitcoinOil Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBbitcoinoild\fP, \fBbitcoinoil.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
